spring:
  application:
    name: hcw-learn-mybatis
  datasource:
    url: jdbc:mysql://47.100.240.207:5555/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9091