spring:
  application:
    name: hcw-learn-mybatis
  datasource:
    druid:
      # MySQL 8.0 以上版本，数据库 URL 需要声明是否使用 SSL 安全验证及指定服务器上的时区
      url: jdbc:mysql://47.100.240.207:5555/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: Root@123
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5 # 初始化时建立物理连接的个数
      max-active: 30 # 最大连接池数量
      min-idle: 5 # 最小连接池数量
      max-wait: 60000  # 获取连接时最大等待时间，单位毫秒
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      test-while-idle: true # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      validation-query: select 1 from dual #用来检测连接是否有效的sql，要求是一个查询语句
      test-on-borrow: false # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      max-pool-prepared-statement-per-connection-size: 50 # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      pool-prepared-statements: true
      filter: stat,wall # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      connection-properties: durid.stat.mergeSql=true;druid.stat.slowSqlMillis=500 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录


server:
  port: 9091
