spring:
  application:
    name: hcw-kafka-springboot-starter
  kafka:
    clientId: hcw-kafka-springboot-starter
    bootstrapServers:
      - node1:9092
      - node2:9092
      - node3:9092
    producer:
      # 重试次数
      retries: 3
      # 批量发送的消息数量
      batch-size: 16384
      # 32MB的批处理缓冲区
      buffer-memory: 33554432
    consumer:
        # 默认消费者组
        group-id: hcw-kafka-springboot-starter
        # 最早未被消费的offset
        auto-offset-reset: earliest
        # 批量一次最大拉取数据量
        max-poll-records: 1000
        # 自动提交
        auto-commit-interval: 1000
        enable-auto-commit: true

server:
  port: 9091

topicName:
  topic1: test
  topic2: test2